#!/usr/bin/env python3
"""Generate deterministic pinyin and furigana candidates for editorial review."""

from __future__ import annotations

import argparse
import json
import logging
import re
import unicodedata
from pathlib import Path
from typing import Any

import jieba
import unidic_lite
from fugashi import Tagger
from pypinyin import Style, pinyin

logging.getLogger("jieba").setLevel(logging.ERROR)

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BOOK = ROOT / "data/china/cities/xian/book.json"
DEFAULT_OUTPUT = ROOT / "build/editorial/xian/reading-candidates.json"
HAN_RE = re.compile(r"[\u3007\u3400-\u4dbf\u4e00-\u9fff]")
HAN_RUN_RE = re.compile(r"([\u3007\u3400-\u4dbf\u4e00-\u9fff]+)")

ZH_OVERRIDES = {
    "兰州": "lánzhōu",
    "兰州大学": "lánzhōu dàxué",
    "兰州西站": "lánzhōu xīzhàn",
    "兰州西站北广场": "lánzhōu xīzhàn běiguǎngchǎng",
    "兰州站": "lánzhōu zhàn",
    "兰州火车站": "lánzhōu huǒchēzhàn",
    "兰州府": "lánzhōufǔ",
    "兰州府城隍庙": "lánzhōufǔ chénghuángmiào",
    "城隍庙": "chénghuángmiào",
    "张掖路": "zhāngyè lù",
    "省政府": "shěng zhèngfǔ",
    "城关区": "chéngguānqū",
    "城关": "chéngguān",
    "金城郡": "jīnchéngjùn",
    "金城县": "jīnchéngxiàn",
    "五泉": "wǔquán",
    "西固": "xīgù",
    "辕门街": "yuánménjiē",
    "甘肃巡抚": "gānsù xúnfǔ",
    "甘肃布政使司": "gānsù bùzhèngshǐsī",
    "巩昌": "gǒngchāng",
    "临洮府": "líntáofǔ",
    "陕甘总督": "shǎn-gān zǒngdū",
    "天兰铁路": "tiānlán tiělù",
    "陇海铁路": "lǒnghǎi tiělù",
    "白塔山": "báitǎshān",
    "白塔山公园": "báitǎshān gōngyuán",
    "甘肃省博物馆": "gānsù shěng bówùguǎn",
    "西津西路": "xījīn xīlù",
    "甘肃彩陶展": "gānsù cǎitáo zhǎn",
    "甘肃佛教艺术展": "gānsù fójiào yìshù zhǎn",
    "甘肃丝绸之路文明展": "gānsù sīchóu zhī lù wénmíng zhǎn",
    "红色甘肃": "hóngsè gānsù",
    "仰韶文化": "yǎngsháo wénhuà",
    "庙底沟类型": "miàodǐgōu lèixíng",
    "石岭下类型": "shílǐngxià lèixíng",
    "秦安": "qín'ān",
    "大地湾": "dàdìwān",
    "甘谷": "gāngǔ",
    "西坪": "xīpíng",
    "鲵鱼": "níyú",
    "鲵鱼纹彩陶瓶": "níyúwén cǎitáopíng",
    "人头形器口彩陶瓶": "réntóuxíng qìkǒu cǎitáopíng",
    "泾川": "jīngchuān",
    "大云寺": "dàyúnsì",
    "五重舍利宝函": "wǔchóng shèlì bǎohán",
    "鎏金铜匣": "liújīn tóngxiá",
    "银椁": "yínguǒ",
    "金棺": "jīnguān",
    "舍利瓶": "shèlìpíng",
    "敦煌": "dūnhuáng",
    "藏经洞": "cángjīngdòng",
    "报父母恩重经变": "bào fùmǔ ēnzhòng jīngbiàn",
    "武威": "wǔwēi",
    "雷台": "léitái",
    "铜奔马": "tóngbēnmǎ",
    "嘉峪关": "jiāyùguān",
    "驿使图": "yìshǐtú",
    "壁画砖": "bìhuàzhuān",
    "魏晋": "wèijìn",
    "棨传": "qǐ chuán",
    "长尾": "chángwěi",
    "黄河": "huánghé",
    "黄河铁桥": "huánghé tiěqiáo",
    "中山桥": "zhōngshānqiáo",
    "将军铁柱": "jiāngjūn tiězhù",
    "镇远浮桥": "zhènyuǎn fúqiáo",
    "钢桁架": "gāng héngjià",
    "穿式钢桁架": "chuānshì gāng héngjià",
    "弧形钢梁": "húxíng gāngliáng",
    "铆接构件": "mǎojiē gòujiàn",
    "白塔寺": "báitǎsì",
    "塔院": "tǎyuàn",
    "系在": "jìzài",
    "背着": "bēizhe",
    "中川机场": "zhōngchuān jīchǎng",
    "中川机场东": "zhōngchuān jīchǎng dōng",
    "可售车次": "kěshòu chēcì",
    "同行人数": "tóngxíng rénshù",
    "一号线": "yīhào xiàn",
    "二号线": "èrhào xiàn",
    "第一行": "dìyī háng",
    "第二行": "dì'èr háng",
    "第三行": "dìsān háng",
    "三行": "sān háng",
    "东方红广场": "dōngfānghóng guǎngchǎng",
    "西关": "xīguān",
    "倒木": "dǎomù",
    "补铺": "bǔpū",
    "大番所": "dàfānsuǒ",
    "甘酒茶屋": "gānjiǔ cháwū",
    "江户口御门": "jiānghùkǒu yùmén",
    "旧街道口": "jiùjiēdàokǒu",
    "杉木林荫道": "shānmù línyīndào",
    "上番休息所": "shàngfān xiūxīsuǒ",
    "箱根关所": "xiānggēn guānsuǒ",
    "御制札": "yùzhìzhá",
    "远见番所": "yuǎnjiàn fānsuǒ",
    "阿房宫": "ēpánggōng",
    "八水": "bāshuǐ",
    "白鹿原": "báilùyuán",
    "兵马俑": "bīngmǎyǒng",
    "兵马俑坑": "bīngmǎyǒngkēng",
    "兵马俑博物馆": "bīngmǎyǒng bówùguǎn",
    "不适": "bùshì",
    "彩绘": "cǎihuì",
    "长安": "cháng'ān",
    "长": "cháng",
    "得": "de",
    "二号坑": "èrhàokēng",
    "丰镐": "fēnghào",
    "丰京": "fēngjīng",
    "封土": "fēngtǔ",
    "滈河": "hàohé",
    "关中": "guānzhōng",
    "汉长安": "hàn cháng'ān",
    "汉长安城": "hàn cháng'ānchéng",
    "皇城": "huángchéng",
    "宫城": "gōngchéng",
    "华清宫": "huáqīnggōng",
    "华清池": "huáqīngchí",
    "华山": "huàshān",
    "华山北站": "huàshān běizhàn",
    "华山南峰": "huàshān nánfēng",
    "汉景帝": "hàn jǐngdì",
    "汉景帝阳陵博物院": "hàn jǐngdì yánglíng bówùyuàn",
    "汉阳陵": "hàn yánglíng",
    "外藏坑": "wàicángkēng",
    "王皇后": "wáng huánghòu",
    "翠华山": "cuìhuáshān",
    "乾陵": "qiánlíng",
    "乾县": "qiánxiàn",
    "乾县站": "qiánxiànzhàn",
    "堰塞湖": "yànsèhú",
    "西安事变": "xī'ān shìbiàn",
    "唐御汤遗址博物馆": "táng yùtāng yízhǐ bówùguǎn",
    "五间厅": "wǔjiāntīng",
    "述圣纪碑": "shùshèngjìbēi",
    "无字碑": "wúzìbēi",
    "永泰公主墓": "yǒngtài gōngzhǔmù",
    "甲片": "jiǎpiàn",
    "将军俑": "jiāngjūnyǒng",
    "临潼": "líntóng",
    "陵园": "língyuán",
    "龙首原": "lóngshǒuyuán",
    "大慈恩寺": "dàcí'ēnsì",
    "大明宫": "dàmínggōng",
    "大秦景教流行中国碑": "dàqín jǐngjiào liúxíng zhōngguó bēi",
    "大唐三藏圣教序": "dàtáng sānzàng shèngjiàoxù",
    "大兴城": "dàxīngchéng",
    "大雁塔": "dàyàntǎ",
    "明清西安": "míng-qīng xī'ān",
    "碑林": "bēilín",
    "传拓": "chuántà",
    "拓包": "tàbāo",
    "哪个": "nǎge",
    "秦岭": "qínlǐng",
    "秦咸阳": "qín xiányáng",
    "秦始皇陵": "qín shǐhuánglíng",
    "秦始皇帝陵": "qín shǐhuángdìlíng",
    "秦始皇帝陵丽山园": "qín shǐhuángdìlíng lìshānyuán",
    "曲尺形": "qūchǐxíng",
    "三号坑": "sānhàokēng",
    "探方": "tànfāng",
    "陶俑": "táoyǒng",
    "未央宫": "wèiyānggōng",
    "少陵原": "shàolíngyuán",
    "舍利": "shèlì",
    "隋大兴": "suí dàxīng",
    "隋大兴城": "suí dàxīngchéng",
    "外郭城": "wàiguōchéng",
    "一号坑": "yīhàokēng",
    "一行行": "yīhángháng",
    "俑坑": "yǒngkēng",
    "台塬": "táiyuán",
    "唐长安": "táng cháng'ān",
    "唐长安城": "táng cháng'ānchéng",
    "褚遂良": "chǔ suìliáng",
    "荐福寺": "jiànfúsì",
    "密檐式": "mìyánshì",
    "景教": "jǐngjiào",
    "景净": "jǐngjìng",
    "经卷": "jīngjuàn",
    "开成石经": "kāichéng shíjīng",
    "吕大忠": "lǚ dàzhōng",
    "吕秀岩": "lǚ xiùyán",
    "墨拓": "mòtà",
    "石台孝经": "shítái xiàojīng",
    "拓本": "tàběn",
    "拓片": "tàpiàn",
    "稍干": "shāogān",
    "重刻": "chóngkè",
    "重排": "chóngpái",
    "西安": "xī'ān",
    "西安北站": "xī'ān běizhàn",
    "西安站": "xī'ānzhàn",
    "西安东站": "xī'ān dōngzhàn",
    "咸阳机场": "xiányáng jīchǎng",
    "咸阳国际机场": "xiányáng guójì jīchǎng",
    "机场": "jīchǎng",
    "航站楼": "hángzhànlóu",
    "网约车": "wǎngyuēchē",
    "出租车": "chūzūchē",
    "地铁": "dìtiě",
    "乘车区": "chéngchēqū",
    "线或": "xiàn huò",
    "同行人": "tóngxíngrén",
    "解放门": "jiěfàngmén",
    "大明宫遗址公园": "dàmínggōng yízhǐ gōngyuán",
    "充电宝": "chōngdiànbǎo",
    "二维码": "èrwéimǎ",
    "直梯": "zhítī",
    "末班车": "mòbānchē",
    "港澳台": "gǎng'àotái",
    "西安碑林博物馆": "xī'ān bēilín bówùguǎn",
    "西安博物院": "xī'ān bówùyuàn",
    "西安府": "xī'ānfǔ",
    "小雁塔": "xiǎoyàntǎ",
    "玄奘": "xuánzàng",
    "聂斯脱里": "nièsītuōlǐ",
    "叙利亚": "xùlìyà",
    "义净": "yìjìng",
    "奉元路": "fèngyuánlù",
    "安定门": "āndìngmén",
    "安远门": "ānyuǎnmén",
    "北广济街": "běiguǎngjìjiē",
    "北院门": "běiyuànmén",
    "长乐门": "chánglèmén",
    "大皮院": "dàpíyuàn",
    "鼓楼": "gǔlóu",
    "广济街": "guǎngjìjiē",
    "化觉巷": "huàjuéxiàng",
    "化觉巷清真大寺": "huàjuéxiàng qīngzhēn dàsì",
    "回坊": "huífāng",
    "回民街": "huímínjiē",
    "礼拜大殿": "lǐbài dàdiàn",
    "莲湖区志": "liánhú qūzhì",
    "南大街": "nándàjiē",
    "清真大寺": "qīngzhēn dàsì",
    "清真寺": "qīngzhēnsì",
    "陕西省志": "shǎnxī shěngzhì",
    "书院门": "shūyuànmén",
    "西安府志": "xī'ān fǔzhì",
    "西大街": "xīdàjiē",
    "西羊市": "xīyángshì",
    "永宁门": "yǒngníngmén",
    "钟楼": "zhōnglóu",
    "周长为": "zhōucháng wéi",
    "均为": "jūn wéi",
    "标为": "biāo wéi",
    "列为": "lièwéi",
    "为准": "wéi zhǔn",
    "走完": "zǒuwán",
    "全程": "quánchéng",
    "全圈": "quánquān",
    "征得": "zhēngdé",
    "四进院落": "sìjìn yuànluò",
    "十三点七四": "shísān diǎn qī sì",
    "一三八四年": "yī sān bā sì nián",
    "一五八二年": "yī wǔ bā èr nián",
    "一三八〇年": "yī sān bā líng nián",
    "一三九二年": "yī sān jiǔ èr nián",
    "七四二年": "qī sì èr nián",
    "一六一九年": "yī liù yī jiǔ nián",
    "一七一一年": "yī qī yī yī nián",
    "一八六五年": "yī bā liù wǔ nián",
    "二〇〇七年": "èr líng líng qī nián",
    "二〇二六年": "èr líng èr liù nián",
    "镐京": "hàojīng",
    "潏河": "juéhé",
    "潏": "jué",
    "渭河": "wèihé",
    "泾河": "jīnghé",
    "沣河": "fēnghé",
    "涝河": "láohé",
    "涝": "láo",
    "浐河": "chǎnhé",
    "灞河": "bàhé",
    "丽山园": "lìshānyuán",
    "弩兵": "nǔbīng",
    "夯土": "hāngtǔ",
    "官网": "guānwǎng",
    "神合": "shénhé",
    "译场": "yìchǎng",
    "白吉馍": "báijímó",
    "biangbiang面": "biangbiangmiàn",
    "报恩寺街": "bào'ēnsìjiē",
    "腊牛肉夹馍": "làniúròujiāmó",
    "腊羊肉夹馍": "làyángròujiāmó",
    "羊肉夹馍": "yángròujiāmó",
    "腊汁肉夹馍": "làzhīròujiāmó",
    "凉皮": "liángpí",
    "擀面皮": "gǎnmiànpí",
    "米皮": "mǐpí",
    "面皮": "miànpí",
    "牛羊肉泡馍": "niúyángròupàomó",
    "泡馍": "pàomó",
    "肉夹馍": "ròujiāmó",
    "肉丸胡辣汤": "ròuwán húlàtāng",
    "洒金桥": "sǎjīnqiáo",
    "少辣": "shǎolà",
    "水围城": "shuǐwéichéng",
    "饦饦馍": "tuōtuōmó",
    "小南门": "xiǎonánmén",
    "油茶麻花": "yóuchá máhuā",
    "永兴坊": "yǒngxīngfāng",
    "甑糕": "zènggāo",
    "臊子": "sàozi",
    "口汤": "kǒutāng",
    "干泡": "gānpào",
    "葫芦头泡馍": "húlutóu pàomó",
    "饺子宴": "jiǎozǐyàn",
    "干拌": "gānbàn",
    "干湿": "gānshī",
    "见长": "jiàncháng",
    "嚼劲": "jiáojìn",
    "为原料": "wéi yuánliào",
    "油泼": "yóupō",
    "一摊接一摊地": "yìtān jiē yìtān de",
    "曲江": "qǔjiāng",
    "粉巷": "fěnxiàng",
    "环城南路": "huánchéng nánlù",
    "慈恩路": "cí'ēnlù",
    "凤城九路": "fèngchéng jiǔlù",
    "悦椿东路": "yuèchūn dōnglù",
    "芷阳广场站": "zhǐyáng guǎngchǎngzhàn",
    "巷道": "xiàngdào",
    "理解为": "lǐjiě wéi",
    "当保证": "dàng bǎozhèng",
    "从葬坑": "cóngzàngkēng",
    "写进行程": "xiějìn xíngchéng",
    "临街房": "línjiēfáng",
    "背街房": "bèijiēfáng",
    "涉外资质": "shèwài zīzhì",
    "陕西历史博物馆": "shǎnxī lìshǐ bówùguǎn",
    "秦始皇帝陵博物院": "qín shǐhuángdìlíng bówùyuàn",
    "中国气象局": "zhōngguó qìxiàngjú",
    "中国环境监测总站": "zhōngguó huánjìng jiāncè zǒngzhàn",
    "国家移民管理局": "guójiā yímín guǎnlǐjú",
    "公安机关": "gōng'ān jīguān",
    "成功订单查询": "chénggōng dìngdān cháxún",
    "实名制": "shímíngzhì",
    "人工通道": "réngōng tōngdào",
    "移动电源": "yídòng diànyuán",
    "急救药物": "jíjiù yàowù",
    "二十四小时内": "èrshísì xiǎoshí nèi",
    "出门前": "chūmén qián",
    "再往": "zài wǎng",
    "哪些": "nǎxiē",
    "不适合": "bù shìhé",
    "同一行": "tóngyī háng",
    "长时间": "chángshíjiān",
    "长距离": "chángjùlí",
    "一一〇": "yāo yāo líng",
    "一一九": "yāo yāo jiǔ",
    "一二〇": "yāo èr líng",
    "二〇二六年八月十六日": "èr líng èr liù nián bā yuè shíliù rì",
    "一九一九年": "yī jiǔ yī jiǔ nián",
    "箱根": "xiānggēn",
    "箱根山": "xiānggēnshān",
    "箱根七汤": "xiānggēn qītāng",
    "箱根十七汤": "xiānggēn shíqītāng",
    "箱根汤本": "xiānggēn tāngběn",
    "箱根登山线": "xiānggēn dēngshānxiàn",
    "在来线": "zàiláixiàn",
    "汤本": "tāngběn",
    "汤坂路": "tāngbǎnlù",
    "小田原": "xiǎotiányuán",
    "小田原城": "xiǎotiányuánchéng",
    "小田原北条氏": "xiǎotiányuán běitiáoshì",
    "马出门": "mǎchūmén",
    "住吉桥": "zhùjíqiáo",
    "铜门": "tóngmén",
    "常盘木门": "chángpánmùmén",
    "本丸": "běnwán",
    "总构": "zǒnggòu",
    "天守橹": "tiānshǒulǔ",
    "附橹": "fùlǔ",
    "渡橹": "dùlǔ",
    "小田急": "xiǎotiánjí",
    "浪漫特快": "làngmàn tèkuài",
    "周游券": "zhōuyóuquàn",
    "畑宿": "tiánsù",
    "三岛": "sāndǎo",
    "三岛大社": "sāndǎo dàshè",
    "源兵卫川": "yuánbīngwèichuān",
    "乐寿园": "lèshòuyuán",
    "东海巴士": "dōnghǎi bāshì",
    "箱根空中步道": "xiānggēn kōngzhōng bùdào",
    "东海道本线": "dōnghǎidào běnxiàn",
    "御殿场": "yùdiànchǎng",
    "御殿场线": "yùdiànchǎngxiàn",
    "乙女峠": "yǐnǚqiǎ",
    "新桥浅间神社": "xīnqiáo qiǎnjiān shénshè",
    "开山仪式": "kāishān yíshì",
    "本殿": "běndiàn",
    "币殿": "bìdiàn",
    "拜殿": "bàidiàn",
    "一五九〇年": "yī wǔ jiǔ líng nián",
    "一九六〇年": "yī jiǔ liù líng nián",
    "一八五四年": "yī bā wǔ sì nián",
    "一八六六年": "yī bā liù liù nián",
    "一九五〇年": "yī jiǔ wǔ líng nián",
    "同行": "tóngxíng",
    "七千一百": "qīqiān yībǎi",
    "为": "wéi",
    "宫之下": "gōngzhīxià",
    "宫城野": "gōngchéngyě",
    "塔之泽": "tǎzhīzé",
    "堂岛": "tángdǎo",
    "底仓": "dǐcāng",
    "木贺": "mùhè",
    "芦之汤": "lúzhītāng",
    "一夜汤治": "yīyè tāngzhì",
    "强罗": "qiángluó",
    "大平台": "dàpíngtái",
    "上大平台": "shàng dàpíngtái",
    "雕刻之森": "diāokè zhī sēn",
    "黏着力": "niánzhuólì",
    "长椅": "chángyǐ",
    "三个": "sān gè",
    "三件": "sān jiàn",
    "一百二十": "yībǎi èrshí",
    "早云山": "zǎoyúnshān",
    "大涌谷": "dàyǒnggǔ",
    "姥子": "lǎozǐ",
    "桃源台": "táoyuántái",
    "芦之湖": "lúzhīhú",
    "仙石原": "xiānshíyuán",
    "元箱根": "yuánxiānggēn",
    "箱根町": "xiānggēntǐng",
    "取得": "qǔdé",
    "空档": "kòngdàng",
    "写下一行": "xiěxià yī háng",
    "神山": "shénshān",
    "驹岳": "jūyuè",
    "冠岳": "guānyuè",
    "大地狱": "dàdìyù",
    "自然研究路": "zìrán yánjiūlù",
    "延命地藏": "yánmìng dìzàng",
    "极乐茶屋": "jílè cháwū",
    "黑鸡蛋馆": "hēijīdànguǎn",
    "硫化氢": "liúhuàqīng",
    "硫化铁": "liúhuàtiě",
    "二〇二六年八月十七日": "èr líng èr liù nián bā yuè shíqī rì",
    "一七八一至一七八九年": "yī qī bā yī zhì yī qī bā jiǔ nián",
    "一泊二食": "yībó èrshí",
    "板蒸鱼糕": "bǎnzhēng yúgāo",
    "板蒸形态": "bǎnzhēng xíngtài",
    "鱼糕": "yúgāo",
    "鱼糜": "yúmí",
    "天明年间": "tiānmíng niánjiān",
    "力饼": "lìbǐng",
    "风祭": "fēngjì",
    "面衣": "miànyī",
    "交叉接触": "jiāochā jiēchù",
    "食用期限": "shíyòng qīxiàn",
    "天妇罗": "tiānfùluó",
    "炸鱼糕": "zhá yúgāo",
    "炸公鱼": "zhá gōngyú",
    "一八七三年": "yī bā qī sān nián",
    "二〇一五年": "èr líng yī wǔ nián",
    "二〇二二年": "èr líng èr èr nián",
    "气象厅": "qìxiàngtīng",
    "国土地理院": "guótǔ dìlǐyuàn",
    "恩赐箱根公园": "ēncì xiānggēn gōngyuán",
    "恩赐箱根公园前": "ēncì xiānggēn gōngyuán qián",
    "箱根神社": "xiānggēn shénshè",
    "旧东海道": "jiù dōnghǎidào",
    "平和鸟居": "pínghé niǎojū",
    "明神鸟居": "míngshén niǎojū",
    "两部鸟居": "liǎngbù niǎojū",
    "手水舍": "shǒushuǐshè",
    "正参道": "zhèngcāndào",
    "万卷上人": "wànjuǎn shàngrén",
    "筥根山缘起并序": "jǔgēnshān yuánqǐ bìngxù",
    "镰仓时代": "liáncāng shídài",
    "源赖朝": "yuán làicháo",
    "二所诣": "èrsuǒyì",
    "芦之湖产": "lúzhīhú chǎn",
    "公鱼": "gōngyú",
    "霞浦": "xiápǔ",
    "神奈川县": "shénnàichuān xiàn",
    "刺网": "cìwǎng",
    "初渔": "chūyú",
    "宫中": "gōngzhōng",
    "南蛮渍": "nánmánzì",
    "甘露煮": "gānlùzhǔ",
    "昆布": "kūnbù",
    "佃煮": "diànzhǔ",
    "箱根离宫": "xiānggēn lígōng",
    "湖畔展望馆": "húpàn zhǎnwàngguǎn",
    "白色花岗岩": "báisè huāgāngyán",
    "国家登录纪念物": "guójiā dēnglù jìniànwù",
    "一一九一年": "yī yī jiǔ yī nián",
    "七五七年": "qī wǔ qī nián",
    "一九五二年": "yī jiǔ wǔ èr nián",
    "一九六四年": "yī jiǔ liù sì nián",
    "一九六五年": "yī jiǔ liù wǔ nián",
    "一九一八年": "yī jiǔ yī bā nián",
    "二〇二五年十二月": "èr líng èr wǔ nián shí'èr yuè",
}

JA_OVERRIDES = {
    "三本": "さんぼん",
    "四段階": "よんだんかい",
    "一組": "ひとくみ",
    "館": "かん",
    "蘭州": "らんしゅう",
    "蘭州大学": "らんしゅうだいがく",
    "蘭州西駅": "らんしゅうにしえき",
    "蘭州駅": "らんしゅうえき",
    "蘭州府": "らんしゅうふ",
    "蘭州府城隍廟": "らんしゅうふじょうこうびょう",
    "城隍廟": "じょうこうびょう",
    "張掖路": "ちょうえきろ",
    "省政府": "しょうせいふ",
    "城関区": "じょうかんく",
    "城関": "じょうかん",
    "金城郡": "きんじょうぐん",
    "金城県": "きんじょうけん",
    "五泉": "ごせん",
    "西固": "せいこ",
    "轅門街": "えんもんがい",
    "甘粛巡撫": "かんしゅくじゅんぶ",
    "甘粛布政使司": "かんしゅくふせいしし",
    "鞏昌": "きょうしょう",
    "臨洮府": "りんとうふ",
    "陝甘総督": "せんかんそうとく",
    "天蘭鉄道": "てんらんてつどう",
    "隴海鉄道": "ろうかいてつどう",
    "兰州西站北广场": "らんしゅうにしえききたひろば",
    "兰州火车站": "らんしゅうえき",
    "白塔山": "はくとうざん",
    "白塔山公園": "はくとうざんこうえん",
    "甘粛省博物館": "かんしゅくしょうはくぶつかん",
    "西津西路": "せいしんせいろ",
    "甘粛彩陶展": "かんしゅくさいとうてん",
    "甘粛仏教芸術展": "かんしゅくぶっきょうげいじゅつてん",
    "甘粛シルクロード文明展": "かんしゅくしるくろーどぶんめいてん",
    "紅色甘粛": "こうしょくかんしゅく",
    "仰韶文化": "ぎょうしょうぶんか",
    "廟底溝型式": "びょうていこうけいしき",
    "石嶺下型式": "せきれいかけいしき",
    "古生物": "こせいぶつ",
    "秦安": "しんあん",
    "大地湾": "だいちわん",
    "甘谷": "かんこく",
    "西坪": "せいへい",
    "鯢魚文彩陶瓶": "げいぎょもんさいとうへい",
    "人頭形器口彩陶瓶": "じんとうけいきこうさいとうへい",
    "黒彩": "こくさい",
    "涇川": "けいせん",
    "大雲寺": "だいうんじ",
    "五重舎利容器": "ごじゅうしゃりようき",
    "石函": "せきかん",
    "鍍金銅箱": "ときんどうばこ",
    "銀槨": "ぎんかく",
    "金棺": "きんかん",
    "舎利瓶": "しゃりびん",
    "敦煌": "とんこう",
    "蔵経洞": "ぞうきょうどう",
    "報父母恩重経変": "ほうふぼおんじゅうきょうへん",
    "武威": "ぶい",
    "雷台": "らいだい",
    "銅奔馬": "どうほんば",
    "嘉峪関": "かよくかん",
    "駅使図": "えきしず",
    "壁画磚": "へきがせん",
    "魏晋": "ぎしん",
    "棨伝": "けいでん",
    "黄河": "こうが",
    "黄河鉄橋": "こうがてっきょう",
    "中山橋": "ちゅうざんきょう",
    "将軍鉄柱": "しょうぐんてっちゅう",
    "鎮遠浮橋": "ちんえんふきょう",
    "白塔寺": "はくとうじ",
    "寺域": "じいき",
    "南詰": "みなみづめ",
    "北詰": "きたづめ",
    "中川空港": "ちゅうせんくうこう",
    "中川机场东": "ちゅうせんくうこうひがし",
    "東方紅広場": "とうほうこうひろば",
    "七里河": "しちりが",
    "西関": "せいかん",
    "一号線": "いちごうせん",
    "二号線": "にごうせん",
    "甘酒茶屋": "あまざけちゃや",
    "入り鉄砲": "いりでっぽう",
    "一里塚": "いちりづか",
    "江戸口御門": "えどぐちごもん",
    "大番所": "おおばんしょ",
    "旧街道口": "きゅうかいどうぐち",
    "上番休息所": "かみばんきゅうそくじょ",
    "杉並木": "すぎなみき",
    "遠見番所": "とおみばんしょ",
    "山道": "やまみち",
    "一日": "いちにち",
    "一館": "いっかん",
    "二館": "にかん",
    "二日": "ふつか",
    "三日": "みっか",
    "四日": "よっか",
    "五日": "いつか",
    "二日間": "ふつかかん",
    "三日間": "みっかかん",
    "四日間": "よっかかん",
    "五日間": "いつかかん",
    "高原": "こうげん",
    "阿房宮": "あぼうきゅう",
    "八水": "はっすい",
    "八つ": "やっつ",
    "白鹿原": "はくろくげん",
    "兵馬俑坑": "へいばようこう",
    "兵馬俑博物館": "へいばようはくぶつかん",
    "版築": "はんちく",
    "歩兵": "ほへい",
    "長安": "ちょうあん",
    "豊鎬": "ほうこう",
    "豊京": "ほうけい",
    "鎬京": "こうけい",
    "滈河": "こうが",
    "関中": "かんちゅう",
    "漢長安": "かんちょうあん",
    "漢長安城": "かんちょうあんじょう",
    "咸陽宮": "かんようきゅう",
    "華清宮": "かせいきゅう",
    "華清池": "かせいち",
    "華山": "かざん",
    "華山北駅": "かざんきたえき",
    "漢景帝": "かんけいてい",
    "漢陽陵": "かんようりょう",
    "景帝": "けいてい",
    "王皇后": "おうこうごう",
    "外蔵坑": "がいぞうこう",
    "陪葬坑": "ばいそうこう",
    "陪葬墓": "ばいそうぼ",
    "陪葬": "ばいそう",
    "翠華山": "すいかざん",
    "乾陵": "けんりょう",
    "乾県": "けんけん",
    "乾県駅": "けんけんえき",
    "堰塞湖": "えんそくこ",
    "西安事件": "せいあんじけん",
    "唐御湯": "とうぎょとう",
    "遺跡博物館": "いせきはくぶつかん",
    "五間庁": "ごけんちょう",
    "驪山": "りざん",
    "西峰": "せいほう",
    "北峰": "ほくほう",
    "五峰": "ごほう",
    "秦陵": "しんりょう",
    "秦": "しん",
    "石海": "せっかい",
    "崩積洞": "ほうせきどう",
    "核心保護区域": "かくしんほごくいき",
    "縦走": "じゅうそう",
    "門闕跡": "もんけつあと",
    "翼馬": "よくば",
    "浮彫": "うきぼり",
    "述聖紀碑": "じゅつせいきひ",
    "無字碑": "むじひ",
    "儀仗": "ぎじょう",
    "帝陵": "ていりょう",
    "主墓室": "しゅぼしつ",
    "未発掘": "みはっくつ",
    "永泰公主墓": "えいたいこうしゅぼ",
    "墓道": "ぼどう",
    "山内": "さんない",
    "皇城": "こうじょう",
    "宮城": "きゅうじょう",
    "軍陣": "ぐんじん",
    "臨潼": "りんどう",
    "陵園": "りょうえん",
    "月": "がつ",
    "龍首原": "りゅうしゅげん",
    "大慈恩寺": "だいじおんじ",
    "大明宮": "だいめいきゅう",
    "大秦景教流行中国碑": "だいしんけいきょうりゅうこうちゅうごくひ",
    "大唐三蔵聖教序": "だいとうさんぞうしょうぎょうじょ",
    "大街": "だいがい",
    "大雁塔": "だいがんとう",
    "明清西安": "みんしんせいあん",
    "明代": "みんだい",
    "密檐式": "みつえんしき",
    "七層": "しちそう",
    "韓建": "かんけん",
    "秦嶺": "しんれい",
    "秦咸陽": "しんかんよう",
    "秦始皇帝陵": "しんしこうていりょう",
    "凹字形": "おうじけい",
    "三号坑": "さんごうこう",
    "陶俑": "とうよう",
    "未央宮": "びおうきゅう",
    "少陵原": "しょうりょうげん",
    "鐘楼": "しょうろう",
    "都城": "とじょう",
    "二関": "にかん",
    "二号坑": "にごうこう",
    "何が": "なにが",
    "何も": "なにも",
    "何を": "なにを",
    "四関": "しかん",
    "四つ": "よっつ",
    "四年": "よねん",
    "大興城": "だいこうじょう",
    "外郭城": "がいかくじょう",
    "一号坑": "いちごうこう",
    "俑坑": "ようこう",
    "唐長安": "とうちょうあん",
    "唐長安城": "とうちょうあんじょう",
    "訳場": "やくじょう",
    "碑林": "ひりん",
    "景教": "けいきょう",
    "景浄": "けいじょう",
    "開成石経": "かいせいせっけい",
    "呂秀岩": "りょしゅうがん",
    "墨拓": "ぼくたく",
    "石台孝経": "せきだいこうきょう",
    "拓本": "たくほん",
    "褚遂良": "ちょすいりょう",
    "西安": "せいあん",
    "西安北駅": "せいあんきたえき",
    "西安駅": "せいあんえき",
    "西安東駅": "せいあんひがしえき",
    "五日前": "いつかまえ",
    "十七時": "じゅうしちじ",
    "来館日": "らいかんび",
    "休館日": "きゅうかんび",
    "出勤日": "しゅっきんび",
    "宿泊日": "しゅくはくび",
    "証明書": "しょうめいしょ",
    "国務院": "こくむいん",
    "月曜日": "げつようび",
    "景区": "けいく",
    "大気質": "たいきしつ",
    "辛い": "からい",
    "一食": "いっしょく",
    "一一〇番": "ひゃくとうばん",
    "一一九番": "ひゃくじゅうきゅうばん",
    "一二〇番": "ひゃくにじゅうばん",
    "陝西歴史博物館": "せんせいれきしはくぶつかん",
    "秦始皇帝陵博物院": "しんしこうていりょうはくぶついん",
    "中国気象局": "ちゅうごくきしょうきょく",
    "中国環境監測総站": "ちゅうごくかんきょうかんそくそうたん",
    "国家移民管理局": "こっかいみんかんりきょく",
    "公安機関": "こうあんきかん",
    "実名確認": "じつめいかくにん",
    "有人通路": "ゆうじんつうろ",
    "予約完了": "よやくかんりょう",
    "交差接触": "こうさせっしょく",
    "一一〇": "いちいちぜろ",
    "一一九": "いちいちきゅう",
    "一二〇": "いちにぜろ",
    "二〇二六年八月十六日": "にせんにじゅうろくねんはちがつじゅうろくにち",
    "西安咸陽国際空港": "せいあんかんようこくさいくうこう",
    "咸陽": "かんよう",
    "空港": "くうこう",
    "机场西": "くうこうにし",
    "机场": "くうこう",
    "十四号線": "じゅうよんごうせん",
    "二号線": "にごうせん",
    "四号線": "よんごうせん",
    "五号線": "ごごうせん",
    "地下鉄": "ちかてつ",
    "到着": "とうちゃく",
    "中国鉄路": "ちゅうごくてつろ",
    "解放門": "かいほうもん",
    "大明宮国家遺跡公園": "だいめいきゅうこっかいせきこうえん",
    "配車": "はいしゃ",
    "重点旅客": "じゅうてんりょかく",
    "保安検査": "ほあんけんさ",
    "身分証明書": "みぶんしょうめいしょ",
    "階": "かい",
    "四人": "よにん",
    "到着口": "とうちゃくぐち",
    "片道乗車券": "かたみちじょうしゃけん",
    "城壁": "じょうへき",
    "南門": "なんもん",
    "雁塔": "がんとう",
    "二〇二五年": "にせんにじゅうごねん",
    "二〇二六年": "にせんにじゅうろくねん",
    "六月三十日": "ろくがつさんじゅうにち",
    "西安碑林博物館": "せいあんひりんはくぶつかん",
    "西安博物院": "せいあんはくぶついん",
    "西安府": "せいあんふ",
    "小雁塔": "しょうがんとう",
    "薦福寺": "せんぷくじ",
    "薦福寺塔": "せんぷくじとう",
    "玄奘": "げんじょう",
    "義浄": "ぎじょう",
    "奉元路": "ほうげんろ",
    "永寧門": "えいねいもん",
    "北院門": "ほくいんもん",
    "化覚巷清真大寺": "かかくこうせいしんだいじ",
    "化覚巷": "かかくこう",
    "清真大寺": "せいしんだいじ",
    "清真寺": "せいしんじ",
    "回族街区": "かいぞくがいく",
    "回民街": "かいみんがい",
    "鼓楼": "ころう",
    "広済街": "こうさいがい",
    "北広済街": "ほくこうさいがい",
    "書院門": "しょいんもん",
    "西大街": "せいだいがい",
    "西羊市": "せいようし",
    "大皮院": "だいひいん",
    "礼拝大殿": "れいはいだいでん",
    "蓮湖区志": "れんこくし",
    "陝西省志": "せんせいしょうし",
    "西安府志": "せいあんふし",
    "南大街": "なんだいがい",
    "一周": "いっしゅう",
    "明初": "みんしょ",
    "環城路": "かんじょうろ",
    "月台": "げつだい",
    "十三・七四": "じゅうさんてんななよん",
    "一三八四年": "せんさんびゃくはちじゅうよねん",
    "一五八二年": "せんごひゃくはちじゅうにねん",
    "一三八〇年": "せんさんびゃくはちじゅうねん",
    "一三九二年": "せんさんびゃくきゅうじゅうにねん",
    "七四二年": "ななひゃくよんじゅうにねん",
    "潏河": "けつが",
    "渭河": "いが",
    "泾河": "けいが",
    "沣河": "ほうが",
    "涝河": "ろうが",
    "浐河": "さんが",
    "灞河": "はが",
    "弩兵": "どへい",
    "甲片": "こうへん",
    "麗山園": "りざんえん",
    "神合": "しんごう",
    "国子監": "こくしかん",
    "呂大忠": "りょだいちゅう",
    "114石": "ひゃくじゅうよんせき",
    "火曜日": "かようび",
    "白吉饃": "ばいじーもー",
    "報恩寺街": "ほうおんじがい",
    "臘牛肉夾饃": "らーにゅうろうじゃーもー",
    "臘羊肉夾饃": "らーやんろうじゃーもー",
    "羊肉夾饃": "やんろうじゃーもー",
    "臘汁肉夾饃": "らーじーろうじゃーもー",
    "臘牛肉": "らーにゅうろう",
    "臘羊肉": "らーやんろう",
    "涼皮": "りゃんぴー",
    "擀面皮": "がんみぇんぴー",
    "米皮": "みーぴー",
    "面皮": "みぇんぴー",
    "牛羊肉泡饃": "にゅうやんろうぱおもー",
    "泡饃": "ぱおもー",
    "肉夾饃": "ろうじゃーもー",
    "肉丸胡辣湯": "ろうわんふーらーたん",
    "洒金橋": "さいきんきょう",
    "水囲城": "しゅいうぇいちょん",
    "飥飥饃": "とぅおとぅおもー",
    "小南門": "しょうなんもん",
    "曲江": "きょくこう",
    "粉巷": "ふんこう",
    "環城南路": "かんじょうなんろ",
    "慈恩路": "じおんろ",
    "鳳城九路": "ほうじょうきゅうろ",
    "悦椿東路": "えっちんとうろ",
    "芷陽広場駅": "しようひろばえき",
    "城壁内": "じょうへきない",
    "階下": "かいか",
    "棟": "とう",
    "西安鐘楼": "せいあんしょうろう",
    "西安南門城壁": "せいあんなんもんじょうへき",
    "西安経開": "せいあんけいかい",
    "西安臨潼": "せいあんりんどう",
    "渉外資格": "しょうがいしかく",
    "油茶麻花": "ようちゃーまーほわー",
    "油潑": "ようぽー",
    "永興坊": "えいこうぼう",
    "甑糕": "ずんがお",
    "臊子": "さおず",
    "口湯": "こうたん",
    "乾泡": "がんぱお",
    "葫蘆頭泡饃": "ふーるーとうぱおもー",
    "餃子宴": "ぎょうざえん",
    "夾饃": "じゃーもー",
    "小吃": "しゃおちー",
    "清真": "せいしん",
    "一か所": "いっかしょ",
    "一品": "いっぴん",
    "一種類": "いっしゅるい",
    "餃子": "ぎょうざ",
    "落花生": "らっかせい",
    "米": "こめ",
    "辛く": "からく",
    "辛さ": "からさ",
    "蒸す": "むす",
    "糖蒜": "たんすわん",
    "通ぶる": "つうぶる",
    "油茶": "ようちゃー",
    "麻花": "まーほわー",
    "饃": "もー",
    "箱根": "はこね",
    "箱根山": "はこねやま",
    "箱根湯本": "はこねゆもと",
    "箱根登山線": "はこねとざんせん",
    "新幹線": "しんかんせん",
    "湯坂路": "ゆさかみち",
    "小田原": "おだわら",
    "小田原城": "おだわらじょう",
    "小田原北条氏": "おだわらほうじょうし",
    "馬出門": "うまだしもん",
    "住吉橋": "すみよしばし",
    "銅門": "あかがねもん",
    "常盤木門": "ときわぎもん",
    "本丸": "ほんまる",
    "総構": "そうがまえ",
    "復興天守": "ふっこうてんしゅ",
    "三重四階": "さんじゅうよんかい",
    "鉄筋コンクリート造": "てっきんコンクリートぞう",
    "天守櫓": "てんしゅやぐら",
    "付櫓": "つけやぐら",
    "渡櫓": "わたりやぐら",
    "城下町": "じょうかまち",
    "小田急": "おだきゅう",
    "東海道新幹線": "とうかいどうしんかんせん",
    "東京": "とうきょう",
    "品川": "しながわ",
    "新宿": "しんじゅく",
    "関西": "かんさい",
    "畑宿": "はたじゅく",
    "三島": "みしま",
    "三嶋大社": "みしまたいしゃ",
    "大社": "たいしゃ",
    "源兵衛川": "げんべえがわ",
    "楽寿園": "らくじゅえん",
    "東海バス": "とうかいバス",
    "箱根スカイウォーク": "はこねスカイウォーク",
    "東海道本線": "とうかいどうほんせん",
    "東海地震": "とうかいじしん",
    "本殿": "ほんでん",
    "幣殿": "へいでん",
    "拝殿": "はいでん",
    "御殿場": "ごてんば",
    "御殿場線": "ごてんばせん",
    "乙女峠": "おとめとうげ",
    "新橋浅間神社": "にいはしせんげんじんじゃ",
    "開山式": "かいざんしき",
    "一五九〇年": "せんごひゃくきゅうじゅうねん",
    "一九六〇年": "せんきゅうひゃくろくじゅうねん",
    "一八五四年": "せんはっぴゃくごじゅうよねん",
    "一八六六年": "せんはっぴゃくろくじゅうろくねん",
    "一・五キロメートル": "いってんごキロメートル",
    "大正期": "たいしょうき",
    "一九五〇年": "せんきゅうひゃくごじゅうねん",
    "一階": "いっかい",
    "三階": "さんがい",
    "上階": "じょうかい",
    "八十分": "はちじゅっぷん",
    "一か月前": "いっかげつまえ",
    "乗車日": "じょうしゃび",
    "三辺": "さんぺん",
    "一軒": "いっけん",
    "一本": "いっぽん",
    "宮ノ下": "みやのした",
    "宮城野": "みやぎの",
    "塔ノ沢": "とうのさわ",
    "強羅": "ごうら",
    "出山": "でやま",
    "出山信号場": "でやましんごうじょう",
    "大平台": "おおひらだい",
    "上大平台": "かみおおひらだい",
    "上大平台信号場": "かみおおひらだいしんごうじょう",
    "小涌谷": "こわきだに",
    "欧米": "おうべい",
    "六十分": "ろくじゅっぷん",
    "九十分": "きゅうじゅっぷん",
    "二十分": "にじゅっぷん",
    "三十分": "さんじゅっぷん",
    "二分": "にふん",
    "二時間": "にじかん",
    "早雲山": "そううんざん",
    "大涌谷": "おおわくだに",
    "姥子": "うばこ",
    "桃源台": "とうげんだい",
    "芦ノ湖": "あしのこ",
    "芦ノ湖畔": "あしのこはん",
    "仙石原": "せんごくはら",
    "元箱根": "もとはこね",
    "彫刻の森": "ちょうこくのもり",
    "時計回り": "とけいまわり",
    "反時計回り": "はんとけいまわり",
    "箱根町": "はこねまち",
    "箱根七湯": "はこねななゆ",
    "一夜湯治": "いちやとうじ",
    "一九六五年": "せんきゅうひゃくろくじゅうごねん",
    "芦之湯": "あしのゆ",
    "箱根園": "はこねえん",
    "翌朝": "よくあさ",
    "降車地点": "こうしゃちてん",
    "実際": "じっさい",
    "玄関": "げんかん",
    "夕朝食": "ゆうちょうしょく",
    "水回り": "みずまわり",
    "一泊二食": "いっぱくにしょく",
    "一行": "いちぎょう",
    "何時": "なんじ",
    "貸切風呂": "かしきりぶろ",
    "客室風呂": "きゃくしつぶろ",
    "朝風呂": "あさぶろ",
    "食事処": "しょくじどころ",
    "神山": "かみやま",
    "駒ヶ岳": "こまがたけ",
    "冠ヶ岳": "かんむりがたけ",
    "大地獄": "おおじごく",
    "自然研究路": "しぜんけんきゅうろ",
    "延命地蔵": "えんめいじぞう",
    "極楽茶屋": "ごくらくちゃや",
    "硫化水素": "りゅうかすいそ",
    "硫化鉄": "りゅうかてつ",
    "安全対策協力金": "あんぜんたいさくきょうりょくきん",
    "臭い": "におい",
    "日本語": "にほんご",
    "約十分": "やくじゅっぷん",
    "四十五分": "よんじゅうごふん",
    "七十五分": "ななじゅうごふん",
    "九十五分": "きゅうじゅうごふん",
    "四十分": "よんじゅっぷん",
    "十五分": "じゅうごふん",
    "一個": "いっこ",
    "四個": "よんこ",
    "一袋": "ひとふくろ",
    "一項": "いっこう",
    "1873年": "せんはっぴゃくななじゅうさんねん",
    "2015年": "にせんじゅうごねん",
    "2022年3月": "にせんにじゅうにねんさんがつ",
    "2026年8月17日": "にせんにじゅうろくねんはちがつじゅうしちにち",
    "10時30分": "じゅうじさんじゅっぷん",
    "15時30分": "じゅうごじさんじゅっぷん",
    "16時": "じゅうろくじ",
    "9時": "くじ",
    "気象庁": "きしょうちょう",
    "国土地理院": "こくどちりいん",
    "水蒸気爆発": "すいじょうきばくはつ",
    "開けた": "ひらけた",
    "外輪山": "がいりんざん",
    "富士山": "ふじさん",
    "恩賜箱根公園": "おんしはこねこうえん",
    "恩賜公園前": "おんしこうえんまえ",
    "箱根神社": "はこねじんじゃ",
    "旧東海道": "きゅうとうかいどう",
    "手水舎": "ちょうずや",
    "正参道": "せいさんどう",
    "万巻上人": "まんがんしょうにん",
    "筥根山縁起并序": "はこねさんえんぎならびにじょ",
    "鎌倉時代": "かまくらじだい",
    "源頼朝": "みなもとのよりとも",
    "二所詣": "にしょもうで",
    "平和の鳥居": "へいわのとりい",
    "明神鳥居": "みょうじんとりい",
    "両部鳥居": "りょうぶとりい",
    "二拝": "にはい",
    "二拍手": "にはくしゅ",
    "一拝": "いっぱい",
    "扁額": "へんがく",
    "霞ヶ浦": "かすみがうら",
    "刺網漁": "さしあみりょう",
    "初漁": "はつりょう",
    "奉納": "ほうのう",
    "宮中": "きゅうちゅう",
    "献上": "けんじょう",
    "南蛮漬け": "なんばんづけ",
    "甘露煮": "かんろに",
    "昆布巻き": "こんぶまき",
    "佃煮": "つくだに",
    "漁業協同組合": "ぎょぎょうきょうどうくみあい",
    "漁協": "ぎょきょう",
    "町の魚": "まちのさかな",
    "板付き蒸しかまぼこ": "いたつきむしかまぼこ",
    "天明年間": "てんめいねんかん",
    "米麹": "こめこうじ",
    "消費期限": "しょうひきげん",
    "風祭": "かざまつり",
    "一杯": "いっぱい",
    "一皿": "ひとさら",
    "一回": "いっかい",
    "二回": "にかい",
    "開いていない": "あいていない",
    "箱根離宮": "はこねりきゅう",
    "湖畔展望館": "こはんてんぼうかん",
    "白御影石": "しろみかげいし",
    "礎石": "そせき",
    "国登録記念物": "くにとうろくきねんぶつ",
    "名勝地関係": "めいしょうちかんけい",
    "1191年": "せんひゃくきゅうじゅういちねん",
    "757年": "ななひゃくごじゅうななねん",
    "1952年": "せんきゅうひゃくごじゅうにねん",
    "1964年": "せんきゅうひゃくろくじゅうよねん",
    "1918年": "せんきゅうひゃくじゅうはちねん",
    "2025年12月": "にせんにじゅうごねんじゅうにがつ",
    "10月1日": "じゅうがつついたち",
    "2月末頃": "にがつまつごろ",
    "老杉": "ろうさん",
    "行先": "ゆきさき",
}

ZH_LITERAL_SPAN_OVERRIDES = {
    key: ZH_OVERRIDES[key]
    for key in (
        "一五九〇年",
        "一九六〇年",
        "一八五四年",
        "一八六六年",
        "一三八〇年",
        "一六一九年",
        "一七一一年",
        "一八六五年",
        "一九五〇年",
        "二〇〇七年",
        "二〇二六年",
        "二〇二六年八月十六日",
        "二〇二六年八月十七日",
        "一九一九年",
        "从葬坑",
        "写进行程",
        "同一行",
        "长时间",
        "长距离",
        "不适合",
        "二十四小时内",
        "出门前",
        "写下一行",
        "一一〇",
        "一一九",
        "一二〇",
        "一一九一年",
        "七五七年",
        "一九五二年",
        "一九六四年",
        "一九六五年",
        "一九一八年",
        "二〇二五年十二月",
        "一七八一至一七八九年",
        "一泊二食",
        "板蒸鱼糕",
        "板蒸形态",
        "鱼糕",
        "鱼糜",
        "天明年间",
        "力饼",
        "风祭",
        "面衣",
        "交叉接触",
        "食用期限",
        "天妇罗",
        "炸鱼糕",
        "炸公鱼",
        "系在",
        "背着",
    )
}


def plain_syllable(value: str) -> str:
    normalized = unicodedata.normalize("NFD", value)
    return "".join(character for character in normalized if not unicodedata.combining(character))


def pinyin_for_word(value: str) -> str:
    if value in ZH_OVERRIDES:
        return ZH_OVERRIDES[value]
    syllables = [
        item[0]
        for item in pinyin(
            value,
            style=Style.TONE,
            heteronym=False,
            strict=False,
            errors=lambda text: list(text),
        )
    ]
    joined = ""
    for syllable in syllables:
        bare = plain_syllable(syllable).lower()
        if joined and bare.startswith(("a", "e", "o")):
            joined += "'"
        joined += syllable.lower()
    return joined


def zh_tokens(value: str) -> list[dict[str, str]]:
    pieces: list[dict[str, str]] = []
    literal_pattern = re.compile(
        "("
        + "|".join(
            re.escape(key)
            for key in sorted(ZH_LITERAL_SPAN_OVERRIDES, key=len, reverse=True)
        )
        + ")"
    )
    for span in filter(None, literal_pattern.split(value)):
        if span in ZH_LITERAL_SPAN_OVERRIDES:
            pieces.append({"text": span, "reading": ZH_LITERAL_SPAN_OVERRIDES[span]})
            continue
        for token in jieba.cut(span, cut_all=False, HMM=False):
            for part in filter(None, HAN_RUN_RE.split(token)):
                item = {"text": part}
                if HAN_RE.search(part):
                    item["reading"] = pinyin_for_word(part)
                pieces.append(item)
    if "".join(item["text"] for item in pieces) != value:
        raise ValueError("Chinese tokenization did not preserve the source text")
    return pieces


def katakana_to_hiragana(value: str) -> str:
    return "".join(
        chr(ord(character) - 0x60) if "\u30a1" <= character <= "\u30f6" else character
        for character in value
    )


def unidic_tagger() -> Tagger:
    options = f"-r {unidic_lite.DICDIR}/mecabrc -d {unidic_lite.DICDIR}"
    return Tagger(options)


def ja_tokens(value: str, tagger: Tagger) -> list[dict[str, str]]:
    override_pattern = re.compile(
        "(" + "|".join(re.escape(key) for key in sorted(JA_OVERRIDES, key=len, reverse=True)) + ")"
    )
    pieces: list[dict[str, str]] = []
    for part in filter(None, override_pattern.split(value)):
        if part in JA_OVERRIDES:
            pieces.append({"text": part, "reading": JA_OVERRIDES[part]})
            continue
        for segment in filter(None, re.split(r"(\s+)", part)):
            if segment.isspace():
                pieces.append({"text": segment})
                continue
            for word in tagger(segment):
                item = {"text": word.surface}
                if HAN_RE.search(word.surface):
                    candidate = word.feature.kana or word.feature.pron
                    if not candidate:
                        raise ValueError(f"missing Japanese reading for {word.surface!r}")
                    item["reading"] = katakana_to_hiragana(candidate)
                pieces.append(item)
    if "".join(item["text"] for item in pieces) != value:
        raise ValueError("Japanese tokenization did not preserve the source text")
    return pieces


def add_candidates(
    document: dict[str, Any],
    status: str = "candidate",
    chapter_ids: set[str] | None = None,
) -> dict[str, Any]:
    tagger = unidic_tagger()
    review_note = (
        "Reviewed against the chapter-specific reading audit."
        if status == "reviewed"
        else "Machine-assisted candidate; editorial review required before publication."
    )
    for chapter in document["chapters"]:
        if chapter_ids is not None and chapter["id"] not in chapter_ids:
            continue
        for block in chapter["blocks"]:
            block["readings"] = {
                "zh": {
                    "system": "hanyu-pinyin-tone-marks",
                    "status": status,
                    "review_notes": [review_note],
                    "tokens": zh_tokens(block["text"]["zh"]),
                },
                "ja": {
                    "system": "furigana",
                    "status": status,
                    "review_notes": [review_note],
                    "tokens": ja_tokens(block["text"]["ja"], tagger),
                },
            }
    return document


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--book", type=Path, default=DEFAULT_BOOK)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--status",
        choices=("candidate", "reviewed"),
        default="candidate",
        help="mark generated layers reviewed only after completing the editorial audit",
    )
    parser.add_argument(
        "--chapter",
        action="append",
        dest="chapter_ids",
        help="update only this chapter; may be repeated (default: all chapters)",
    )
    args = parser.parse_args()

    for word in ZH_OVERRIDES:
        jieba.add_word(word, freq=2_000_000)
    document = json.loads(args.book.read_text(encoding="utf-8"))
    chapter_ids = set(args.chapter_ids) if args.chapter_ids else None
    if chapter_ids is not None:
        known_ids = {chapter["id"] for chapter in document["chapters"]}
        unknown_ids = sorted(chapter_ids - known_ids)
        if unknown_ids:
            parser.error(f"unknown chapter id(s): {', '.join(unknown_ids)}")
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(
            add_candidates(document, args.status, chapter_ids),
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"reading candidates: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
